import "rxjs/add/operator/debounceTime";
import "rxjs/add/operator/distinctUntilChanged";
import { OnInit, ElementRef } from '@angular/core';
import { PerfectScrollbarComponent } from 'angular2-perfect-scrollbar';
import { FontPickerService } from './font-picker.service';
import { Font, GoogleFontInterface } from './interfaces';
export declare class DialogComponent implements OnInit {
    private el;
    private service;
    open: boolean;
    private loading;
    private top;
    private left;
    private position;
    private font;
    private initialFont;
    private styles;
    private testWidth;
    private testContainer;
    private listLabel;
    private selectedFont;
    private presetVisible;
    private arrowTop;
    private fontAmount;
    private loadedFonts;
    private presetFonts;
    private googleFonts;
    private currentFonts;
    private fpWidth;
    private fpHeight;
    private fpPosition;
    private fpPositionOffset;
    private fpPresetLabel;
    private fpPresetFonts;
    private fpSizeSelect;
    private fpStyleSelect;
    private fpCancelButton;
    private fpCancelButtonText;
    private fpCancelButtonClass;
    private fpUploadButton;
    private fpUploadButtonText;
    private fpUploadButtonClass;
    private dialogArrowSize;
    private dialogArrowOffset;
    private listenerResize;
    private listenerMouseDown;
    private directiveInstance;
    private directiveElementRef;
    private searchTerm;
    private config;
    dialogElement: any;
    scrollbar: PerfectScrollbarComponent;
    constructor(el: ElementRef, service: FontPickerService);
    ngOnInit(): void;
    setDialog(instance: any, elementRef: ElementRef, font: Font, fpPosition: string, fpPositionOffset: string, fpPositionRelativeToArrow: boolean, fpPresetLabel: any, fpPresetFonts: any, fpUploadButton: boolean, fpUploadButtonClass: string, fpUploadButtonText: string, fpStyleSelect: boolean, fpSizeSelect: boolean, fpCancelButton: boolean, fpCancelButtonClass: string, fpCancelButtonText: string, fpHeight: string, fpWidth: string): void;
    updateDialog(font: Font, fpPosition: string, fpPositionOffset: string, fpPositionRelativeToArrow: boolean, fpPresetLabel: any, fpPresetFonts: any, fpUploadButton: boolean, fpUploadButtonClass: string, fpUploadButtonText: string, fpStyleSelect: boolean, fpSizeSelect: boolean, fpCancelButton: boolean, fpCancelButtonClass: string, fpCancelButtonText: string, fpHeight: string, fpWidth: string): void;
    openFontPicker(): void;
    closeFontPicker(): void;
    isFontAvailable(font: Font): boolean;
    getPresetFonts(): any[];
    setDisplayedFontSource(): void;
    setCurentFonts(target: Font[]): void;
    findFont(searchVal: any, exactMatch?: boolean): Font;
    findFonts(searchVal: any, exactMatch?: boolean): Font[];
    loadMoreFonts(): void;
    loadGoogleFonts(fonts: Font[]): void;
    searchGoogleFonts(value: string): void;
    convertGoogleFont(font: GoogleFontInterface): Font;
    onResize(): void;
    onMouseDown(event: any): void;
    onUploadFiles(): void;
    onCancelSelect(): void;
    onSelectFont(font: any): void;
    onSearchReset(event?: any): void;
    onFontStyleChange($event: any, font: Font): void;
    isDescendant(parent: any, child: any): boolean;
    createDialogBox(element: any, offset: any): any;
    setDialogPosition(): void;
}
